# Pre-Commit
# https://pre-commit.com
# Run formatter and more before git commit.
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-merge-conflict
-   repo: local
    hooks:
      - id: gofmt
        name: gofmt
        language: golang
        entry: fmt
        files: \.go$
        require_serial: true
-   repo: local
    hooks:
      - id: goimports
        name: goimports
        language: golang
        entry: goimports
        files: \.go$
        args:
        - -w
        require_serial: true
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.59.1
    hooks:
    -   id: golangci-lint
        exclude: ^pkg/
