# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test and QA

on:
  push:
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - name: Quality Assurance
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        gofmt -l ./*.go
        goimports -e -d ./*.go
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
    - name: Tests
      env:
        SQLITE_CONNECTION_STRING: ${{ vars.SQLITE_CONNECTION_STRING }}
        SQLITE_USER: ${{ secrets.SQLITE_USER }}
        SQLITE_PASSWORD: ${{ secrets.SQLITE_PASSWORD }}
        SQLITE_API_KEY: ${{ secrets.SQLITE_API_KEY }}
        SQLITE_HOST: ${{ vars.SQLITE_HOST }}
        SQLITE_DB: ${{ vars.SQLITE_DB }}
        SQLITE_PORT: ${{ vars.SQLITE_PORT }}
      run: make test-codecov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
